### Creation of ground data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from src.postprocessing.visualization import ernesto_plotter
from src.postprocessing.metrics import compute_metrics, _mse

In [2]:
df_ground = pd.read_csv("../../data/external/paper_dic24/invecchiamento/DT_EIG_ALL_FILES_AGING.csv", delimiter='\t')

In [3]:
df_ground

,Timestamp,Tdiff [s],Tensione Cella 1 [V],Tensione Cella 2 [V],Tensione Cella 3 [V],Tensione Cella 4 [V],Tensione Cella 5 [V],Tensione Cella 6 [V],Tensione Cella 7 [V],Tensione Cella 8 [V],Tensione Cella 9 [V],Tensione Cella 10 [V],Tensione Cella 11 [V],Tensione Cella 12 [V],Tensione Cella 13 [V],Tensione Cella 14 [V],Tensione Modulo 1 [V],Corrente Modulo 1 [A],Temperatura Modulo 1 [°C],Temperatura Ambiente 1 [°C]
0,2024-05-09 15:49:11.722,445.821,4.160,4.160,4.159,4.160,4.153,4.153,4.160,4.160,4.154,4.154,4.153,4.156,4.152,4.153,29.045,0.000,26.747,25.440
1,2024-05-09 15:49:11.951,0.229,4.160,4.160,4.159,4.160,4.153,4.153,4.160,4.160,4.154,4.154,4.154,4.156,4.152,4.153,29.041,-0.027,26.747,25.440
2,2024-05-09 15:49:12.951,1.000,4.161,4.160,4.159,4.159,4.153,4.153,4.160,4.160,4.154,4.154,4.154,4.156,4.152,4.153,29.044,0.027,26.747,25.502
3,2024-05-09 15:49:13.957,1.006,4.161,4.160,4.159,4.160,4.153,4.153,4.160,4.160,4.154,4.154,4.154,4.156,4.152,4.154,29.045,-0.134,26.747,25.440
4,2024-05-09 15:49:14.958,1.001,4.161,4.160,4.159,4.160,4.153,4.153,4.160,4.160,4.154,4.154,4.154,4.156,4.152,4.153,29.043,0.080,26.747,25.440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9020828,2024-09-30 08:44:07.206,1.000,3.102,3.101,2.886,2.886,2.636,2.635,2.654,2.654,2.471,2.471,2.722,2.724,2.981,2.982,19.406,-0.027,11.774,11.650
9020829,2024-09-30 08:44:08.207,1.001,3.101,3.101,2.886,2.886,2.636,2.636,2.654,2.654,2.471,2.471,2.722,2.724,2.981,2.982,19.406,0.027,11.774,11.650
9020830,2024-09-30 08:44:09.205,0.998,3.101,3.101,2.886,2.886,2.636,2.636,2.654,2.654,2.471,2.471,2.722,2.724,2.981,2.982,19.407,0.187,11.774,11.681
9020831,2024-09-30 08:44:10.205,1.000,3.102,3.101,2.886,2.886,2.636,2.635,2.654,2.654,2.471,2.471,2.722,2.724,2.981,2.982,19.405,0.027,11.805,11.681
9020832,2024-09-30 08:44:11.206,1.000,3.101,3.101,2.886,2.886,2.635,2.636,2.654,2.654,2.471,2.471,2.722,2.724,2.981,2.982,19.405,0.187,11.805,11.712

In [22]:
#columns_to_drop = ['Tensione Modulo 1 [V]', 'Tensione Cella 1 [V]', 'Tensione Cella 2 [V]', 'Tensione Cella 13 [V]', 'Tensione Cella 14 [V]' ]

In [23]:
#df_ground = df_ground.drop(columns=columns_to_drop)

In [24]:
#df_ground['Tensione Modulo [V]'] = df_ground[[col for col in df_ground.columns if col.startswith('Tensione Cella')]].mean(axis=1)

In [25]:
#df_ground

In [4]:
columns_to_keep = ['Timestamp', 'Tdiff [s]', 'Corrente Modulo 1 [A]', 'Tensione Cella 1 [V]', 'Temperatura Modulo 1 [°C]', 'Temperatura Ambiente 1 [°C]']

In [5]:
df_ground = df_ground[columns_to_keep]

In [6]:
columns_new_names = {'Timestamp': 'Time', 
                     'Corrente Modulo 1 [A]': 'Corrente[A]', 
                     'Tensione Modulo [V]': 'Tensione[V]', 
                     'Tensione Cella 1 [V]': 'Tensione[V]', 
                     'Temperatura Modulo 1 [°C]': 'Temperatura[degC]', 
                     'Temperatura Ambiente 1 [°C]':'T_ambiente[degC]'
                    }

In [7]:
df_ground = df_ground.rename(columns=columns_new_names)

In [8]:
df_ground['Corrente[A]'] /= 2

In [9]:
df_ground['Corrente[A]'] *= -1

In [10]:
df_ground = df_ground.dropna(axis=0).reset_index()

In [11]:
df_ground = df_ground.drop(columns=['index'])

In [12]:
df_ground

,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
0,2024-05-09 15:49:11.722,445.821,-0.0000,4.160,26.747,25.440
1,2024-05-09 15:49:11.951,0.229,0.0135,4.160,26.747,25.440
2,2024-05-09 15:49:12.951,1.000,-0.0135,4.161,26.747,25.502
3,2024-05-09 15:49:13.957,1.006,0.0670,4.161,26.747,25.440
4,2024-05-09 15:49:14.958,1.001,-0.0400,4.161,26.747,25.440
...,...,...,...,...,...,...
9020820,2024-09-30 08:44:07.206,1.000,0.0135,3.102,11.774,11.650
9020821,2024-09-30 08:44:08.207,1.001,-0.0135,3.101,11.774,11.650
9020822,2024-09-30 08:44:09.205,0.998,-0.0935,3.101,11.774,11.681
9020823,2024-09-30 08:44:10.205,1.000,-0.0135,3.102,11.805,11.681
9020824,2024-09-30 08:44:11.206,1.000,-0.0935,3.101,11.805,11.712

In [21]:
df_ground[3369121:7642382].to_csv("../../data/ground/paper_dic24/aging_cella1_CU2-4.csv", index=False)

In [14]:
df_ground[df_ground['Time'] ==  '2024-07-01 17:51:37.216']

,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
3369120,2024-07-01 17:51:37.216,1.006,-0.0135,3.432,26.529,25.066

In [15]:
df_ground[df_ground['Time'] ==  '2024-07-28 16:51:29.485']

,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
5233222,2024-07-28 16:51:29.485,0.998,0.147,3.387,27.276,25.44

In [16]:
df_ground[df_ground['Time'] ==  '2024-09-05 09:40:58.437']

,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
7642381,2024-09-05 09:40:58.437,0.998,0.067,3.386,26.56,25.813

In [163]:
df_ground[3944860:3944865]

,index,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
3944860,3944862,2024-07-08 13:01:44.592,1.004,-0.0400,3.473571,40.879,37.829
3944861,3944863,2024-07-08 13:01:45.601,1.009,-0.0400,3.473429,40.879,37.829
3944862,3944864,2024-07-08 13:01:46.601,0.999,-0.0400,3.473286,40.879,37.891
3944863,3944865,2024-07-08 13:01:47.601,1.000,-0.0135,3.473286,40.848,37.953
3944864,3944866,2024-07-08 13:01:48.601,1.000,-0.0935,3.473286,40.848,37.984

In [128]:
len(df_ground[:3944862])

3944862

In [130]:
df_ground[:3944863].tail()

,Time,Tdiff [s],Corrente[A],Tensione[V],Temperatura[degC],T_ambiente[degC]
3944858,2024-07-08 13:01:40.579,1.004,0.0670,3.473714,40.879,37.829
3944859,2024-07-08 13:01:41.587,1.007,-0.0670,3.473429,40.879,37.829
3944860,2024-07-08 13:01:42.587,1.000,-0.0135,3.473857,40.879,37.829
3944861,2024-07-08 13:01:43.587,1.000,-0.0670,3.473286,40.879,37.860
3944862,2024-07-08 13:01:44.592,1.004,-0.0400,3.473571,40.879,37.829

### Creation of parameters

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from src.postprocessing.visualization import ernesto_plotter
from src.postprocessing.metrics import compute_metrics, _mse

In [2]:
pathfile = "../../data/external/paper_dic24/invecchiamento/Parametrizzazione_celle_modulo/DT_parameters_2RC_3T_4CU_module_avg_cell.xlsx"

xls = pd.ExcelFile(pathfile)
df_params = {sheet_name: xls.parse(sheet_name) for sheet_name in xls.sheet_names}

In [3]:
sheets_to_read = ['CU1', 'CU2', 'CU3', 'CU4',]

In [4]:
df_params[sheets_to_read[0]]

,soc,r0,r1,c1,r2,c2,ocv,temp
0,1.0,0.003874,0.003552,16900.773037,0.000668,2.379500e+06,4.054794,10
1,0.9,0.004085,0.003473,16479.444643,0.000566,2.924559e+06,4.038000,10
2,0.8,0.004444,0.004680,13699.631407,0.000990,1.574526e+06,3.939600,10
3,0.7,0.004701,0.004466,14722.774198,0.002488,5.511692e+05,3.849800,10
4,0.6,0.004816,0.004151,14356.688734,0.000958,1.563374e+06,3.750367,10
5,0.5,0.005070,0.004323,15032.408702,0.000989,1.409207e+06,3.696233,10
6,0.4,0.005204,0.004616,13261.911937,0.001660,6.146816e+05,3.661467,10
7,0.3,0.005553,0.005165,13172.693739,0.002366,5.764786e+05,3.632233,10
8,0.2,0.006002,0.005785,8837.756172,0.002238,5.373800e+05,3.583667,10
9,0.1,0.008468,0.009762,2697.213258,0.002474,3.874581e+05,3.520367,10
10,0.0,0.008232,0.034568,208.562097,0.005947,7.939393e+04,3.485333,10
11,1.0,0.002448,0.002577,18336.767747,0.000713,3.427603e+06,4.060987,25
12,0.9,0.002466,0.002264,18390.098502,0.000545,4.101995e+06,4.041767,25
13,0.8,0.002691,0.002994,17463.963735,0.000778,3.010835e+06,3.945900,25
14,0.7,0.002680,0.003554,20908.025217,0.001401,9.955191e+05,3.860400,25
15,0.6,0.002832,0.002580,20473.165737,0.000886,2.099663e+06,3.763167,25
16,0.5,0.002893,0.002617,20085.631875,0.000708,2.446688e+06,3.705867,25
17,0.4,0.003049,0.003068,21837.478068,0.000874,1.641956e+06,3.670233,25
18,0.3,0.003036,0.003340,22714.166193,0.001342,9.184794e+05,3.641133,25
19,0.2,0.003109,0.003230,19034.662076,0.001006,1.802031e+06,3.594000,25
20,0.1,0.003179,0.003592,14060.330873,0.001121,2.207088e+06,3.539400,25
21,0.0,0.004111,0.006660,6281.671259,0.002287,1.068210e+06,3.477867,25
22,1.0,0.001871,0.002007,21195.840720,0.000454,3.346052e+06,4.065292,40
23,0.9,0.001862,0.001619,22120.287263,0.000407,5.208302e+06,4.043800,40
24,0.8,0.001981,0.002219,19807.227744,0.000578,3.874211e+06,3.947800,40
25,0.7,0.001943,0.002936,23611.409838,0.000814,1.763900e+06,3.861400,40
26,0.6,0.001988,0.001852,29497.925351,0.000559,3.331039e+06,3.764700,40
27,0.5,0.002002,0.001899,25790.522054,0.000444,3.534645e+06,3.707600,40
28,0.4,0.002041,0.002410,27648.534293,0.000499,2.782055e+06,3.671467,40
29,0.3,0.002129,0.002482,30185.816154,0.000821,1.588453e+06,3.639367,40
30,0.2,0.002058,0.002154,24807.162480,0.000825,7.220416e+06,3.587400,40
31,0.1,0.002231,0.002114,22637.897139,0.000780,8.342916e+06,3.530800,40
32,0.0,0.002416,0.003263,15924.720490,0.001842,2.459425e+06,3.463800,40

In [34]:
folder = "../../data/external/paper_dic24/invecchiamento/Capacita_persa_invecchiamento/"
files = os.listdir(folder)

temps = ['10degC', '25degC', '40degC']
soh_dict = {}

for f in files:
    xls = pd.ExcelFile(folder + f)
    logic = [temp in f for temp in temps]
    soh_dict[np.array(temps)[logic][0]] = xls.parse('SoH')

In [35]:
soh_dict

{'40degC':   Prova               Timestamp       Cmax       SoH
 0   CU1 2024-05-23 17:45:03.852  21.231530  1.000000
 1   CU2 2024-07-08 13:01:44.592  20.929465  0.985773
 2   CU3 2024-08-05 18:10:50.379  20.674144  0.973747
 3   CU4 2024-09-26 14:18:23.764  19.332055  0.910535,
 '25degC':   Prova               Timestamp       Cmax       SoH
 0   CU1 2024-05-26 16:02:05.663  20.964156  1.000000
 1   CU2 2024-07-01 17:51:37.216  20.950225  0.999335
 2   CU3 2024-07-28 16:51:29.485  20.199415  0.963521
 3   CU4 2024-09-05 09:40:58.437  19.474334  0.928935,
 '10degC':   Prova               Timestamp       Cmax       SoH
 0   CU1 2024-05-19 12:54:43.119  21.674894  1.000000
 1   CU2 2024-07-05 00:42:15.020  21.449010  0.989579
 2   CU3 2024-08-02 09:23:26.960  20.802485  0.959750
 3   CU4 2024-09-28 13:43:09.173  19.120141  0.882133}

In [36]:
soh = []

for cu in range(4):
    soh.append([soh_dict[temp]['SoH'][cu] for temp in temps])

In [37]:
soh

[[1.0, 1.0, 1.0],
 [0.9895785482815977, 0.9993354589540778, 0.9857728052660962],
 [0.959750265148424, 0.9635214707394952, 0.9737472545400517],
 [0.8821331004219448, 0.9289347767052692, 0.9105351965798174]]

In [43]:
for i, sheet in enumerate(sheets_to_read):
    soh_values = [soh[i][0]] * 11 + [soh[i][1]] * 11 + [soh[i][2]] * 11
    df_params[sheet]['soh'] = soh_values

In [49]:
df_params['CU4']

,soc,r0,r1,c1,r2,c2,ocv,temp,soh
0,1.0,0.003881,0.002918,18344.314849,0.000953,1.265391e+06,4.033698,10,0.882133
1,0.9,0.004510,0.003439,14299.263451,0.000859,1.191511e+06,4.024067,10,0.882133
2,0.8,0.005108,0.004886,14623.697226,0.001559,9.932802e+05,3.916833,10,0.882133
3,0.7,0.005247,0.004198,15652.239300,0.002151,7.959682e+05,3.807700,10,0.882133
4,0.6,0.005646,0.003852,16614.072952,0.001390,1.329444e+06,3.722600,10,0.882133
5,0.5,0.005427,0.004737,13113.689848,0.001540,8.904463e+05,3.674500,10,0.882133
6,0.4,0.006264,0.004745,13872.966332,0.002200,5.393698e+05,3.643500,10,0.882133
7,0.3,0.006617,0.005740,9346.690270,0.002569,5.517479e+05,3.605667,10,0.882133
8,0.2,0.008429,0.007828,4380.781925,0.002466,6.036833e+05,3.548000,10,0.882133
9,0.1,0.011123,0.030314,403.965414,0.006191,1.211967e+05,3.485100,10,0.882133
10,0.0,0.009977,0.094294,1214.796486,0.073588,2.405747e+04,3.350867,10,0.882133
11,1.0,0.002920,0.002712,19485.510037,0.000975,1.837400e+06,4.043415,25,0.928935
12,0.9,0.003071,0.002403,17809.061961,0.000698,2.043132e+06,4.030400,25,0.928935
13,0.8,0.003132,0.003423,17555.377802,0.001181,1.745248e+06,3.926033,25,0.928935
14,0.7,0.003129,0.003115,22100.008759,0.001675,1.099437e+06,3.820700,25,0.928935
15,0.6,0.003246,0.002607,23468.928392,0.001153,1.858476e+06,3.735000,25,0.928935
16,0.5,0.003259,0.003041,21980.940237,0.000984,1.927500e+06,3.684333,25,0.928935
17,0.4,0.003346,0.003477,22871.019790,0.001210,1.271890e+06,3.652067,25,0.928935
18,0.3,0.003533,0.003206,22376.926623,0.001495,1.157053e+06,3.612000,25,0.928935
19,0.2,0.003712,0.003300,17509.944067,0.001344,1.771021e+06,3.557933,25,0.928935
20,0.1,0.004029,0.005413,7542.184845,0.001856,1.205117e+06,3.498600,25,0.928935
21,0.0,0.004971,0.070118,2145.293351,0.052439,4.006433e+04,3.298467,25,0.928935
22,1.0,0.002098,0.002067,20227.650094,0.000786,1.433399e+06,4.045542,40,0.910535
23,0.9,0.002090,0.001625,16908.423493,0.000580,1.239518e+06,4.030100,40,0.910535
24,0.8,0.002249,0.002503,19642.534448,0.000961,2.039790e+06,3.926133,40,0.910535
25,0.7,0.002224,0.002504,27664.966485,0.001303,1.574564e+06,3.821967,40,0.910535
26,0.6,0.002240,0.001936,28146.419122,0.000914,2.678838e+06,3.735933,40,0.910535
27,0.5,0.002296,0.002259,26788.832057,0.000751,3.070299e+06,3.686467,40,0.910535
28,0.4,0.002334,0.002632,28981.773999,0.000863,2.187607e+06,3.653700,40,0.910535
29,0.3,0.002378,0.002233,28753.315426,0.000990,2.350017e+06,3.607700,40,0.910535
30,0.2,0.002430,0.002153,22578.008729,0.001193,2.885629e+06,3.553933,40,0.910535
31,0.1,0.002766,0.002655,16796.720598,0.001729,2.039036e+06,3.494233,40,0.910535
32,0.0,0.003075,0.058736,2874.223512,0.051822,5.693658e+04,3.242800,40,0.910535

In [81]:
df_complete = df_params['CU1']

In [82]:
for sheet in sheets_to_read[1:]:
    df_complete = pd.concat([df_complete, df_params[sheet]], ignore_index=True)

In [83]:
df_complete

,soc,r0,r1,c1,r2,c2,ocv,temp,soh
0,1.0,0.003874,0.003552,16900.773037,0.000668,2.379500e+06,4.054794,10,1.000000
1,0.9,0.004085,0.003473,16479.444643,0.000566,2.924559e+06,4.038000,10,1.000000
2,0.8,0.004444,0.004680,13699.631407,0.000990,1.574526e+06,3.939600,10,1.000000
3,0.7,0.004701,0.004466,14722.774198,0.002488,5.511692e+05,3.849800,10,1.000000
4,0.6,0.004816,0.004151,14356.688734,0.000958,1.563374e+06,3.750367,10,1.000000
...,...,...,...,...,...,...,...,...,...
127,0.4,0.002334,0.002632,28981.773999,0.000863,2.187607e+06,3.653700,40,0.910535
128,0.3,0.002378,0.002233,28753.315426,0.000990,2.350017e+06,3.607700,40,0.910535
129,0.2,0.002430,0.002153,22578.008729,0.001193,2.885629e+06,3.553933,40,0.910535
130,0.1,0.002766,0.002655,16796.720598,0.001729,2.039036e+06,3.494233,40,0.910535
131,0.0,0.003075,0.058736,2874.223512,0.051822,5.693658e+04,3.242800,40,0.910535

In [84]:
#df_complete.to_csv('../../data/config/params/lookup_module_2exp.csv', index=False)